# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'UILabel_ContentSize_Demo' do
#pod 'UITableView+FDTemplateLayoutCell'
#pod 'UIViewController+Swizzled'
pod 'UILabel+ContentSize'
end

target 'UILabel_ContentSize_DemoUITests' do

end

